jobs:
  deploy:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v29
    - run: nix develop .#book -c mdbook build ./.
    - if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/book/
    - if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/deploy-pages@v4
name: Deploy to GitHub Pages
'on':
  push:
    branches:
    - main
