jobs:
  deploy:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permission:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v29
    - run: nix develop .#book -c mdbook build ./.
    - if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/book
name: Deploy to GitHub Pages
'on':
  push:
    branches:
    - main
