jobs:
  deploy:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v29
    - run: nix develop .#book -c mdbook build ./.
    - if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/book/
    - id: deployment
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/deploy-pages@v4
name: Deploy to GitHub Pages
'on':
  push:
    branches:
    - main
